<a href="https://colab.research.google.com/github/cxbxmxcx/GenReality/blob/master/GEN_7_Attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
#@title Imports and Input tensor x
import torch
import numpy as np

x = np.random.randint(0,3,(3,4))
x = torch.tensor(x, dtype=torch.float32)
print(x)

tensor([[1., 1., 0., 1.],
        [1., 0., 1., 2.],
        [2., 0., 1., 1.]])


In [40]:
#@title Create random key, query and value weights
w_key = np.random.randint(0,2,(4,3))
w_query = np.random.randint(0,2,(4,3))
w_value = np.random.randint(0,4,(4,3))

w_key = torch.tensor(w_key, dtype=torch.float32)
w_query = torch.tensor(w_query, dtype=torch.float32)
w_value = torch.tensor(w_value, dtype=torch.float32)
print(w_key)
print(w_query)
print(w_value)

tensor([[0., 0., 0.],
        [1., 0., 1.],
        [1., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 0., 0.],
        [0., 1., 1.],
        [0., 1., 1.]])
tensor([[2., 2., 0.],
        [0., 0., 3.],
        [2., 1., 0.],
        [2., 2., 1.]])


In [41]:
#@title Multiply by x
keys = x @ w_key
querys = x @ w_query
values = x @ w_value

print(keys)
print(querys)
print(values)

tensor([[1., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 3., 3.],
        [2., 2., 2.]])
tensor([[4., 4., 4.],
        [8., 7., 2.],
        [8., 7., 1.]])


In [42]:
#@title Calculate Attention Score
attn_scores = querys @ keys.T
print(attn_scores)

tensor([[2., 1., 1.],
        [4., 1., 1.],
        [4., 2., 2.]])


In [43]:
#@title Apply Softmax
from torch.nn.functional import softmax

attn_scores_softmax = softmax(attn_scores, dim=-1)
print(attn_scores_softmax)

tensor([[0.5761, 0.2119, 0.2119],
        [0.9094, 0.0453, 0.0453],
        [0.7870, 0.1065, 0.1065]])


In [44]:
#@title Calculate Weighted Values and Outputs
weighted_values = values[:,None] * attn_scores_softmax.T[:,:,None]

outputs = weighted_values.sum(dim=0)
print(outputs)

tensor([[5.6955, 5.2716, 2.9403],
        [4.3622, 4.2717, 3.7736],
        [4.8521, 4.6390, 3.4675]])
